### ISSUE TITLE
training script

### ISSUE THREAD

**Issue by nlpLover123** [DeepPathology/MIDOG_reference_docker#2]
Hi, will the training code be provided ? I am wondering whether the original training data is processed the same as the test data (in this repository, create overlapping patches for the whole image).  Or directly resize to 512*512

**Comment by FraukeWilm** [comment]
Hi, please have a look at our introductory jupyter notebook on Colab: https://colab.research.google.com/drive/1uQNnpldgypSWX304QrVzvRjN5cKygn0B

There you can find an example of how to create a dataloader similar to the one that was used for training the reference algorithm.

**Comment by nlpLover123** [comment]
Thanks for your quick reply.
